# Generated by Django 4.2 on 2023-04-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ast20', '__first__'),
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psjsipadd',
            name='PsEndpoints',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='ast20.psendpoints'),
        ),
        migrations.AlterField(
            model_name='psjsipadd',
            name='aors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aors', to='ast20.psaors'),
        ),
        migrations.AlterField(
            model_name='psjsipadd',
            name='auth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth', to='ast20.psauths'),
        ),
    ]
