# Generated by Django 4.2 on 2023-04-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_psjsipadd_psendpoints_alter_psjsipadd_aors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=40, null=True)),
                ('callid', models.CharField(default='', max_length=32)),
                ('queuename', models.CharField(default='', max_length=32)),
                ('agent', models.CharField(default='', max_length=32)),
                ('event', models.CharField(default='', max_length=32)),
                ('data1', models.CharField(default='', max_length=255)),
                ('data2', models.CharField(default='', max_length=255)),
                ('data3', models.CharField(default='', max_length=255)),
                ('data4', models.CharField(default='', max_length=255)),
                ('data5', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'queue_log2',
            },
        ),
    ]
