# Generated by Django 4.2 on 2023-04-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ast20', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psjsipadd',
            options={'verbose_name': 'PsjsipAdd', 'verbose_name_plural': 'PsjsipAdd'},
        ),
        migrations.AlterModelTable(
            name='psjsipadd',
            table='PsjsipAdd',
        ),
    ]
