# Generated by Django 4.2 on 2023-04-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ast20', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueMembers',
            fields=[
                ('interface', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('membername', models.CharField(blank=True, max_length=80, null=True)),
                ('state_interface', models.CharField(blank=True, max_length=80, null=True)),
                ('penalty', models.IntegerField(blank=True, null=True)),
                ('paused', models.IntegerField(blank=True, null=True)),
                ('uniqueid', models.IntegerField(unique=True)),
                ('wrapuptime', models.IntegerField(blank=True, null=True)),
                ('ringinuse', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'queue_members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Queues',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('musiconhold', models.CharField(blank=True, default='default', max_length=128, null=True)),
                ('announce', models.CharField(blank=True, max_length=128, null=True)),
                ('context', models.CharField(blank=True, max_length=128, null=True)),
                ('timeout', models.IntegerField(blank=True, default=15, null=True)),
                ('ringinuse', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3, null=True)),
                ('setinterfacevar', models.CharField(blank=True, max_length=3, null=True)),
                ('setqueuevar', models.CharField(blank=True, max_length=3, null=True)),
                ('setqueueentryvar', models.CharField(blank=True, max_length=3, null=True)),
                ('monitor_format', models.CharField(blank=True, max_length=8, null=True)),
                ('membermacro', models.CharField(blank=True, max_length=512, null=True)),
                ('membergosub', models.CharField(blank=True, max_length=512, null=True)),
                ('queue_youarenext', models.CharField(blank=True, max_length=128, null=True)),
                ('queue_thereare', models.CharField(blank=True, max_length=128, null=True)),
                ('queue_callswaiting', models.CharField(blank=True, max_length=128, null=True)),
                ('queue_quantity1', models.CharField(blank=True, max_length=128, null=True)),
                ('queue_quantity2', models.CharField(blank=True, max_length=128, null=True)),
                ('queue_holdtime', models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=128, null=True)),
                ('queue_minutes', models.CharField(blank=True, max_length=128, null=True)),
                ('queue_minute', models.CharField(blank=True, max_length=128, null=True)),
                ('queue_seconds', models.CharField(blank=True, max_length=128, null=True)),
                ('queue_thankyou', models.CharField(blank=True, max_length=128, null=True)),
                ('queue_callerannounce', models.CharField(blank=True, max_length=128, null=True)),
                ('queue_reporthold', models.CharField(blank=True, max_length=128, null=True)),
                ('announce_frequency', models.IntegerField(blank=True, null=True)),
                ('announce_to_first_user', models.CharField(blank=True, max_length=3, null=True)),
                ('min_announce_frequency', models.IntegerField(blank=True, null=True)),
                ('announce_round_seconds', models.IntegerField(blank=True, null=True)),
                ('announce_holdtime', models.CharField(blank=True, max_length=128, null=True)),
                ('announce_position', models.CharField(blank=True, max_length=128, null=True)),
                ('announce_position_limit', models.IntegerField(blank=True, null=True)),
                ('periodic_announce', models.CharField(blank=True, max_length=50, null=True)),
                ('periodic_announce_frequency', models.IntegerField(blank=True, null=True)),
                ('relative_periodic_announce', models.CharField(blank=True, max_length=3, null=True)),
                ('random_periodic_announce', models.CharField(blank=True, max_length=3, null=True)),
                ('retry', models.IntegerField(blank=True, default=5, null=True)),
                ('wrapuptime', models.IntegerField(blank=True, default=5, null=True)),
                ('penaltymemberslimit', models.IntegerField(blank=True, null=True)),
                ('autofill', models.CharField(blank=True, max_length=3, null=True)),
                ('monitor_type', models.CharField(blank=True, max_length=128, null=True)),
                ('autopause', models.CharField(blank=True, max_length=3, null=True)),
                ('autopausedelay', models.IntegerField(blank=True, null=True)),
                ('autopausebusy', models.CharField(blank=True, max_length=3, null=True)),
                ('autopauseunavail', models.CharField(blank=True, max_length=3, null=True)),
                ('maxlen', models.IntegerField(blank=True, null=True)),
                ('servicelevel', models.IntegerField(blank=True, null=True)),
                ('strategy', models.CharField(blank=True, choices=[('ringall', 'Ring All'), ('leastrecent', 'Least Recent'), ('fewestcalls', 'Fewest Calls'), ('random', 'Random'), ('roundrobin', 'roundrobin'), ('rrmemory', 'Round Robin Memory'), ('linear', 'Linear'), ('wrandom', 'Weighted Random'), ('rrordered', 'Round Robin Ordered')], max_length=11, null=True)),
                ('joinempty', models.CharField(blank=True, max_length=128, null=True)),
                ('leavewhenempty', models.CharField(blank=True, max_length=128, null=True)),
                ('reportholdtime', models.CharField(blank=True, max_length=3, null=True)),
                ('memberdelay', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('timeoutrestart', models.CharField(blank=True, max_length=3, null=True)),
                ('defaultrule', models.CharField(blank=True, max_length=128, null=True)),
                ('timeoutpriority', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'queues',
                'managed': False,
            },
        ),
    ]
