# Generated by Django 4.2 on 2023-04-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ast20', '0002_queuemembers_queues'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=40, null=True)),
                ('callid', models.CharField(db_index=True, default='', max_length=32)),
                ('queuename', models.CharField(db_index=True, default='', max_length=32)),
                ('agent', models.CharField(db_index=True, default='', max_length=32)),
                ('event', models.CharField(db_index=True, default='', max_length=32)),
                ('data', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'queue_log',
            },
        ),
    ]
