# Generated by Django 4.2 on 2023-04-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ast20', '0002_alter_psjsipadd_options_alter_psjsipadd_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psauths',
            name='PsjsipAdd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PJSIP', to='ast20.psjsipadd'),
        ),
    ]
