# Generated by Django 4.2 on 2023-04-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ast20', '0003_alter_psauths_psjsipadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psaors',
            name='PsjsipAdd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PsAors', to='ast20.psjsipadd'),
        ),
        migrations.AlterField(
            model_name='psauths',
            name='PsjsipAdd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PsAuths', to='ast20.psjsipadd'),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='PsjsipAdd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PsEndpoints', to='ast20.psjsipadd'),
        ),
    ]
