# Generated by Django 4.2 on 2023-04-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ast20', '0003_queuelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queuelog',
            old_name='data',
            new_name='data1',
        ),
        migrations.AddField(
            model_name='queuelog',
            name='data2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='queuelog',
            name='data3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='queuelog',
            name='data4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='queuelog',
            name='data5',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='queuelog',
            name='agent',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='queuelog',
            name='callid',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='queuelog',
            name='event',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='queuelog',
            name='queuename',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='queuelog',
            name='time',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
