# Generated by Django 4.2 on 2023-04-23 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ast20', '0005_alter_psaors_psjsipadd_alter_psauths_psjsipadd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psjsipadd',
            name='ps_aors',
            field=models.ForeignKey(blank=True, default='Değer', on_delete=django.db.models.deletion.CASCADE, to='ast20.psaors'),
        ),
        migrations.AddField(
            model_name='psjsipadd',
            name='ps_auths',
            field=models.ForeignKey(blank=True, default='Değer', on_delete=django.db.models.deletion.CASCADE, to='ast20.psauths'),
        ),
        migrations.AddField(
            model_name='psjsipadd',
            name='ps_endpoints',
            field=models.ForeignKey(blank=True, default='Değer', on_delete=django.db.models.deletion.CASCADE, to='ast20.psendpoints'),
        ),
        migrations.AlterField(
            model_name='psaors',
            name='PsjsipAdd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='psauths',
            name='PsjsipAdd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='PsjsipAdd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
