# Generated by Django 4.2 on 2023-04-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ast20', '0006_psjsipadd_ps_aors_psjsipadd_ps_auths_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psendpoints',
            name='aggregate_mwi',
            field=models.CharField(blank=True, default='yes', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='allow_subscribe',
            field=models.CharField(blank=True, default='yes', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='context',
            field=models.CharField(blank=True, default='testing', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='cos_audio',
            field=models.IntegerField(blank=True, default='5', null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='cos_video',
            field=models.IntegerField(blank=True, default='4', null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='deny',
            field=models.CharField(blank=True, default='0.0.0.0/0', max_length=95, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='device_state_busy_at',
            field=models.IntegerField(blank=True, default='3', null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='direct_media',
            field=models.CharField(blank=True, default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='dtmf_mode',
            field=models.CharField(blank=True, default='rfc4733', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='force_rport',
            field=models.CharField(blank=True, default='yes', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='ice_support',
            field=models.CharField(blank=True, default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='inband_progress',
            field=models.CharField(blank=True, default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='media_encryption',
            field=models.CharField(blank=True, default='no', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='media_encryption_optimistic',
            field=models.CharField(blank=True, default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='media_use_received_transport',
            field=models.CharField(blank=True, default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='moh_suggest',
            field=models.CharField(blank=True, default='default', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='one_touch_recording',
            field=models.CharField(blank=True, default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='permit',
            field=models.CharField(blank=True, default='0.0.0.0/0', max_length=95, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='record_off_feature',
            field=models.CharField(blank=True, default='apprecord', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='record_on_feature',
            field=models.CharField(blank=True, default='apprecord', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='rewrite_contact',
            field=models.CharField(blank=True, default='yes', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='rtcp_mux',
            field=models.CharField(blank=True, default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='rtp_symmetric',
            field=models.CharField(blank=True, default='yes', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='rtp_timeout',
            field=models.IntegerField(blank=True, default='120', null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='rtp_timeout_hold',
            field=models.IntegerField(blank=True, default='300', null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='send_connected_line',
            field=models.CharField(blank=True, default='yes', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='send_pai',
            field=models.CharField(blank=True, default='yes', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='timers',
            field=models.CharField(blank=True, default='yes', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='tos_audio',
            field=models.CharField(blank=True, default='ef', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='tos_video',
            field=models.CharField(blank=True, default='af41', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='transport',
            field=models.CharField(blank=True, default='transport-udp', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='trust_id_inbound',
            field=models.CharField(blank=True, default='yes', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='use_avpf',
            field=models.CharField(blank=True, default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='psendpoints',
            name='user_eq_phone',
            field=models.CharField(blank=True, default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='psjsipadd',
            name='allow',
            field=models.CharField(blank=True, default='ulaw,alaw,g722,gsm,vp9,vp8,h264', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='psjsipadd',
            name='auth_type',
            field=models.CharField(blank=True, default='userpass', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='psjsipadd',
            name='context',
            field=models.CharField(blank=True, default='testing', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='psjsipadd',
            name='deny',
            field=models.CharField(blank=True, default='0.0.0.0/0', max_length=95, null=True),
        ),
        migrations.AlterField(
            model_name='psjsipadd',
            name='direct_media',
            field=models.CharField(blank=True, default='no', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='psjsipadd',
            name='disallow',
            field=models.CharField(blank=True, default='all', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='psjsipadd',
            name='max_contacts',
            field=models.IntegerField(blank=True, default='1', null=True),
        ),
        migrations.AlterField(
            model_name='psjsipadd',
            name='permit',
            field=models.CharField(blank=True, default='0.0.0.0/0', max_length=95, null=True),
        ),
        migrations.AlterField(
            model_name='psjsipadd',
            name='qualify_frequency',
            field=models.IntegerField(blank=True, default='30', null=True),
        ),
        migrations.AlterField(
            model_name='psjsipadd',
            name='transport',
            field=models.CharField(blank=True, default='transport-udp', max_length=40, null=True),
        ),
    ]
