# Generated by Django 4.2 on 2023-04-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ast20', '0007_alter_psendpoints_aggregate_mwi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CdrTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clid', models.CharField(blank=True, max_length=80, null=True)),
                ('src', models.CharField(blank=True, max_length=80, null=True)),
                ('dst', models.CharField(blank=True, max_length=80, null=True)),
                ('dcontext', models.CharField(blank=True, max_length=80, null=True)),
                ('channel', models.CharField(blank=True, max_length=80, null=True)),
                ('dstchannel', models.CharField(blank=True, max_length=80, null=True)),
                ('lastapp', models.CharField(blank=True, max_length=80, null=True)),
                ('lastdata', models.CharField(blank=True, max_length=80, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('billsec', models.IntegerField(blank=True, null=True)),
                ('disposition', models.CharField(blank=True, max_length=45, null=True)),
                ('amaflags', models.IntegerField(blank=True, null=True)),
                ('accountcode', models.CharField(blank=True, max_length=20, null=True)),
                ('uniqueid', models.CharField(blank=True, max_length=150, null=True)),
                ('userfield', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Cdr_Tables',
                'verbose_name_plural': 'Cdr_Tables',
                'db_table': 'CdrTables',
            },
        ),
    ]
