# Generated by Django 4.2 on 2023-04-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ast20', '0008_cdrtables'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustemCdrTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.CharField(blank=True, max_length=80, null=True)),
                ('Privilege', models.CharField(blank=True, max_length=80, null=True)),
                ('SequenceNumber', models.CharField(blank=True, max_length=80, null=True)),
                ('File', models.CharField(blank=True, max_length=80, null=True)),
                ('Line', models.CharField(blank=True, max_length=80, null=True)),
                ('Func', models.CharField(blank=True, max_length=80, null=True)),
                ('AccountCode', models.CharField(blank=True, max_length=80, null=True)),
                ('Source', models.CharField(blank=True, max_length=80, null=True)),
                ('Destination', models.CharField(blank=True, max_length=80, null=True)),
                ('DestinationContext', models.CharField(blank=True, max_length=80, null=True)),
                ('CallerID', models.CharField(blank=True, max_length=80, null=True)),
                ('Channel', models.CharField(blank=True, max_length=80, null=True)),
                ('DestinationChannel', models.CharField(blank=True, max_length=80, null=True)),
                ('LastApplication', models.CharField(blank=True, max_length=80, null=True)),
                ('LastData', models.CharField(blank=True, max_length=80, null=True)),
                ('StartTime', models.CharField(blank=True, max_length=80, null=True)),
                ('AnswerTime', models.CharField(blank=True, max_length=80, null=True)),
                ('EndTime', models.CharField(blank=True, max_length=80, null=True)),
                ('Duration', models.IntegerField(blank=True, null=True)),
                ('BillableSeconds', models.IntegerField(blank=True, null=True)),
                ('Disposition', models.CharField(blank=True, max_length=80, null=True)),
                ('AMAFlags', models.IntegerField(blank=True, null=True)),
                ('UniqueID', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'verbose_name': 'CustemCdr_Tables',
                'verbose_name_plural': 'CustemCdr_Tables',
                'db_table': 'CustemCdrTables',
            },
        ),
    ]
