# Generated by Django 4.2 on 2023-04-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ast20', '0009_custemcdrtables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custemcdrtables',
            name='AMAFlags',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
