# Generated by Django 4.2 on 2023-04-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ast20', '0010_alter_custemcdrtables_amaflags'),
    ]

    operations = [
        migrations.AddField(
            model_name='custemcdrtables',
            name='Calltype',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='custemcdrtables',
            name='Carrier',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='custemcdrtables',
            name='Companyid',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='custemcdrtables',
            name='Likid',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='custemcdrtables',
            name='Rate',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='custemcdrtables',
            name='Recordid',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='custemcdrtables',
            name='Specialid',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='custemcdrtables',
            name='UserField',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
